version: "3.5"

services:
    postgres-db:
        container_name: pgdb
        image: postgres:13
        restart: always
        ports:
            - 5432:5432
        networks:
            - backend
        volumes:
            - ./postgres:/appdb
        environment:
            POSTGRES_USER: coworkdbadmin
            POSTGRES_PASSWORD: "password123"
            POSTGRES_DB: cowork
            PGDATA: /appdb
    application:
        container_name: app
        build:
            context: .
        restart: always
        ports:
            - 5000:5000
        networks:
            - backend
        volumes:
            - .:/opt/application/flask
        depends_on:
            - postgres-db

networks:
    backend:
      driver: "bridge"


