"""empty message

Revision ID: c57413f027bb
Revises: 0385dc117c59
Create Date: 2022-01-15 13:47:16.957100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57413f027bb'
down_revision = '0385dc117c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('calendar', sa.Column('webhook_id', sa.String(length=255), nullable=True))
    op.add_column('calendar', sa.Column('expiration', sa.String(length=255), nullable=True))
    op.drop_column('event', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('calendar', 'expiration')
    op.drop_column('calendar', 'webhook_id')
    op.drop_column('calendar', 'resource_id')
    # ### end Alembic commands ###
